// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

let client: any;
if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
} else {
  const noop = async () => ({ data: null, error: null });
  const auth = {
    getUser: async () => ({ data: { user: null } }),
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe() {} } } }),
    signInWithPassword: noop,
    signOut: async () => ({ error: null }),
  };
  const from = (_table: string) => ({
    select: noop,
    insert: noop,
    delete: noop,
    eq: (_col: string, _val: unknown) => ({ select: noop, single: noop }),
    single: noop,
  });
  client = { auth, from };
}

export const supabase = client as ReturnType<typeof createClient<Database>>;
